version: '3'

services:
  informix:
    build: .
    tty: true
    environment:
      LICENSE: 'accept'
    ports:
      - 9088:9088
      - 9089:9089
      - 27017:27017 # enables mongo connection
      - 27018:27018 # enables rest connection
      - 27883:27883
    privileged: true
