.1
To add a row to the database, type the information
about the customer into the spaces between the brackets,
which are called "fields."  The label to the
right of a field tells what type of information
the field should contain.

After you've filled in one field, press RETURN to move the
cursor to the next field.  When you have filled the last
field, press ESCAPE or RETURN to add this customer to the
database.  If you want to add the customer without filling
in all fields, press ESCAPE.

When the program prompts you, type "y" to add another
customer, or type "n" to return to the CUSTOMER Menu.
.2
To search the database for information about a parti-
cular customer, type the customer's last name.
The program will find all the customers with the
given last name and display the first customer on the screen.

When the menu prompts you, enter RETURN if you want to
see information about the next customer with the 
given name.  Otherwise, type "y" to return to the menu.
At this point you can modify the customer information 
currently on your screen or delete the customer from
the database, if you choose.
.3
To modify a customer row, first use the query function to
find the customer row you want to modify.  Once the
customer row is on the screen, select the modify option.
Then use the arrow keys to move the cursor to any field you
want to change and enter the new information.  When you have
finished making changes, press ESCAPE to return to the menu.
.4
To delete a customer from the database, first use the
query function to find the customer row you want to 
delete.  Then select the delete option and type "y" to
delete the row or "n" if you decide not to delete the row.
.5
Select this option to leave the CUSTOMER Menu.
